name: Continuous Deployment (CD)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
env:
  REGISTRY: ghcr.io

jobs:
  create-release:
    name: Create new release
    uses: remla23-team5/cicd/.github/workflows/publish-with-tag.yaml@feature/release-docker
#  create-release:
#    name: Create new release
#    uses: remla23-team5/cicd/.github/workflows/release.yaml@main
#  publish-docker:
#    name: Publish Docker image
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    needs: create-release
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 19
#        uses: actions/setup-java@v3
#        with:
#          java-version: '19'
#          distribution: 'temurin'
#
#      - name: Update app version
#        run: |
#          mvn -q versions:set -DnewVersion="${{ needs.create-release.outputs.version }}"
#
#      - name: Build with Maven
#        run: |
#          mvn clean package -DskipTests --batch-mode --update-snapshots
#
#      - name: Log in to the Container registry
#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4.0.0
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ env.REGISTRY }}/${{ github.repository }}:latest,
#            ${{ env.REGISTRY }}/${{ github.repository }}:${{ needs.create-release.outputs.version }}