name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@test
  publish-docker:
    needs: release
    uses: remla23-team5/cicd/.github/workflows/publish-docker.yaml@test
    with:
      version_tag: ${{ needs.release.outputs.version_tag }}
      image_name: ${{ github.repository }}
