name: Continuous Deployment (CD)

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+(-SNAPSHOT)"]

env:
  REGISTRY: ghcr.io

jobs:
  create-release:
    name: Create new release
    uses: remla23-team5/cicd/.github/workflows/publish-with-tag.yaml@feature/release-docker
