name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
env:
  REGISTRY: ghcr.io

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@test
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Update version
        run: |
          mvn -q versions:set -DnewVersion="${{ needs.release.outputs.version }}"
          echo "$(cat pom.xml)"

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots clean package -DskipTests

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: echo
        run: |
          echo "[version]: ${{ needs.release.outputs.version }}"
          echo "[version_tag]: v${{ needs.release.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
           ${{ env.REGISTRY }}/${{ github.repository }}:latest,
           ${{ env.REGISTRY }}/${{ github.repository }}:${{ needs.release.outputs.version }}
