name: Create release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: remla23-team5/cicd/.github/workflows/release.yaml@main
  publish:
    needs: release
    uses: remla23-team5/cicd/.github/workflows/publish-docker.yaml@0.0.3
    with:
      image_name: ${{ github.repository }}
