name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  release:
    uses: ./.github/workflows/release.yaml
  echo:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "[version_tag]: ${{ needs.release.outputs.version_tag }}"
      # - name: publish
      #   uses: ./.github/workflows/publish-docker.yaml@main
      #   with:
      #     version_tag: ${{ steps.release.outputs.version_tag }}
      #     image_name: ${{ github.repository }}
