name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: remla23-team5/cicd/.github/workflows/release.yaml@main
      - name: echo
        run: |
          echo "[version_tag]: ${{ inputs.version }}"
      # - name: publish
      #   uses: ./.github/workflows/publish-docker.yaml@main
      #   with:
      #     version_tag: ${{ steps.release.outputs.version_tag }}
      #     image_name: ${{ github.repository }}
