name: Java CI

on:
  pull_request:
    branches:
      - main

jobs:
  app-ci:
    name: java-ci
    uses: remla23-team5/cicd/.github/workflows/java-ci.yaml@main
    with:
      ARTIFACT_NAME: app.jar
