name: Tag & Create Snapshot Release

on:
  push:
    branches-ignore:
      - "main"

jobs:
  create-snapshot-release:
    name: Create new snapshot release
    if: startsWith('snapshot:', ${{ github.event.head_commit.message }})
    uses: remla23-team5/cicd/.github/workflows/snapshot.yaml@update-release-snapshot
    secrets: inherit
  publish-docker:
    name: Build docker image and publish to registry
    needs: create-release
    uses: remla23-team5/cicd/.github/workflows/publish-docker.yaml@update-release-snapshot
    with:
      version: ${{ needs.create-release.outputs.version }}
      image_name: app
    secrets: inherit
