name: Tag & Create Release

on: [workflow_dispatch, push]

jobs:
  create-release:
    name: Create new release
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    uses: remla23-team5/cicd/.github/workflows/release.yaml@update-release-snapshot
    secrets: inherit
  create-snapshot-release:
    name: Create new snapshot release
    if: github.ref != 'refs/heads/main' && startsWith('snapshot:', ${{ github.event.head_commit.message }})
    uses: remla23-team5/cicd/.github/workflows/snapshot.yaml@update-release-snapshot
    secrets: inherit
